<script type="text/javascript">
    Payment.prototype.save = Payment.prototype.save.wrap(function (save) {

        var validator = new Validation(this.form);

        if (this.validate() && validator.validate()) {

            var methodCode = this.currentMethod;

            if (methodCode == 'spryng_creditcard') {
                var requestToken = true;
                var cardToken = $(methodCode + '_card_token').getValue();
                var spryngOrganisation = '<?php echo Mage::helper('spryng')->getOrganisation('spryng_creditcard'); ?>';
                var spryngAccount = '<?php echo Mage::helper('spryng')->getOrganisation('spryng_creditcard'); ?>';
                var spryngApiEndpoint = '<?php echo Mage::helper('spryng')->getApiEndpoint('card'); ?>';
            } else if (methodCode == 'spryng_bancontact') {
                var requestToken = true;
                var cardToken = $(methodCode + '_card_token').getValue();
                var spryngOrganisation = '<?php echo Mage::helper('spryng')->getOrganisation('spryng_bancontact'); ?>';
                var spryngAccount = '<?php echo Mage::helper('spryng')->getOrganisation('spryng_bancontact'); ?>';
                var spryngApiEndpoint = '<?php echo Mage::helper('spryng')->getApiEndpoint('card'); ?>';
            } else {
                var requestToken = false;
                var cardToken = '';
            }

            if (requestToken && (0 === cardToken.length)) {

                $(methodCode + '_card_token').setValue('');
                $(methodCode + '_cc_number').disable();
                $(methodCode + '_expiration').disable();
                $(methodCode + '_expiration_yr').disable();
                $(methodCode + '_cc_cid').disable();

                var callSuccess = function (res) {

                    var response = window.JSON.parse(res.responseText);

                    $(methodCode + '_card_token').setValue(response._id);
                    $(methodCode + '_cc_number').setValue('');
                    $(methodCode + '_expiration').setValue('');
                    $(methodCode + '_expiration_yr').setValue('');
                    $(methodCode + '_cc_cid').setValue('');

                    $(methodCode + '_cc_number').enable();
                    $(methodCode + '_expiration').enable();
                    $(methodCode + '_expiration_yr').enable();
                    $(methodCode + '_cc_cid').enable();

                    if (response._id) {
                        save();
                    } else {
                        alert(Translator.translate('Error in processing data, please try again').stripTags());
                        return false;
                    }
                };

                var callError = function (res) {
                    $(methodCode + '_cc_number').enable();
                    $(methodCode + '_expiration').enable();
                    $(methodCode + '_expiration_yr').enable();
                    $(methodCode + '_cc_cid').enable();

                    alert(Translator.translate('Error in request, please try again').stripTags());
                    return false;
                };

                var setRequestHeaders = function (res) {
                    var t = res.transport;
                    t.setRequestHeader = t.setRequestHeader.wrap(function (original, k, v) {
                        if (/^(accept|accept-language|content-language)$/i.test(k))
                            return original(k, v);
                        if (/^content-type$/i.test(k) &&
                            /^(application\/x-www-form-urlencoded|multipart\/form-data|text\/plain)(;.+)?$/i.test(v))
                            return original(k, v);
                    });
                };

                var data =
                    {
                        card_number: $(methodCode + '_cc_number').getValue(),
                        expiry_month: $(methodCode + '_expiration').getValue(),
                        expiry_year: $(methodCode + '_expiration_yr').getValue(),
                        cvv: $(methodCode + '_cc_cid').getValue(),
                        organisation: spryngOrganisation,
                        account: spryngAccount
                    };

                new Ajax.Request(spryngApiEndpoint, {
                    method: 'POST',
                    parameters: data,
                    onSuccess: callSuccess,
                    onFailure: callError,
                    onCreate: setRequestHeaders
                });

            } else {
                save();
            }
        }
    });
</script>