<?php
/**
 * Copyright © 2017 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

$_code = $this->getMethodCode();
$_prefixes = Mage::helper('spryng')->getCustomerPrefixes();
$_paymentClasses = Mage::helper('spryng')->getPaymentClasses($_code);
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_pclass" class="required"><em>*</em><?php echo $this->__('Pclass:') ?></label>
        <span class="input-box">
            <select id="<?php echo $_code; ?>_pclass" name="payment[pclass]" title="<?php echo $_code ?>_pclass" class="required-entry input-text">
                <?php foreach ($_paymentClasses as $class) { ?>
                    <option value="<?php echo $class['id'] ?>"><?php echo $class['name'] ?></option>
                <?php } ?>
            </select>
        </span>
    </li>
    <li>
        <label for="<?php echo $_code ?>_prefix" class="required"><em>*</em><?php echo $this->__('Prefix:') ?></label>
        <span class="input-box">
            <select id="<?php echo $_code; ?>_prefix" name="payment[prefix]" title="<?php echo $_code ?>_prefix" class="required-entry input-text">
                <?php foreach ($_prefixes as $prefix) { ?>
                    <option value="<?php echo $prefix['id'] ?>"><?php echo $prefix['name'] ?></option>
                <?php } ?>
            </select>
        </span>
    </li>
    <li>
        <label for="<?php echo $_code ?>_dob" class="required"><em>*</em><?php echo $this->__('Date of Birth (DD/MM/YYYY)') ?>
        </label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_dob" name="payment[dob]" title="<?php echo $this->__('Date of Birth') ?>" value="" class="input-text required-entry"/>
        </div>
    </li>
</ul>