<?php
/**
 * Copyright © 2017 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

$_code = $this->getMethodCode();
$_prefixes = Mage::helper('spryng')->getCustomerPrefixes();
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_prefix" class="required"><em>*</em><?php echo $this->__('Prefix:') ?></label>
        <span class="input-box">
            <select id="<?php echo $_code; ?>_prefix" name="payment[prefix]" title="<?php echo $_code ?>_prefix" class="required-entry input-text">
                <?php foreach ($_prefixes as $prefix) { ?>
                    <?php if (isset($prefix['id']) && isset($prefix['id'])) { ?>
                        <option value="<?php echo $prefix['id'] ?>"><?php echo $prefix['name'] ?></option>
                    <?php } ?>
                <?php } ?>
            </select>
        </span>
    </li>
</ul>